---
after_script:
  - "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
before_install:
  - "gem update --system"
  - "gem install bundler"
before_script:
  - "bundle exec rails db:create RAILS_ENV=test"
  - "bundle exec rails db:migrate RAILS_ENV=test"

language: ruby
script:
  - "bundle exec rspec"
