---

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
  - "gem update --system"
  - "gem install bundler"
before_script:
  - "bundle exec rails db:create RAILS_ENV=test"
  - "bundle exec rails db:migrate RAILS_ENV=test"
deploy:
  provider: heroku
  api_key:
    secure: 6241042e-c771-4103-ae7a-f8974724b3b5
  app: steam-acebook
  on:
    repo: stuartpet/acebook-steam
  true: ~
language: ruby
script:
  - "bundle exec rspec"
